services:
  postgres:
    image: postgis/postgis:16-3.5-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME:-database}
      POSTGRES_USER: ${POSTGRES_USERNAME:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-hackme}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
    driver: local

networks:
  local:
    driver: bridge
