spring:
  # Templates reloading during development launch
  thymeleaf:
    cache: false

  # Static resources reloading during development launch
  web:
    resources:
      cache.period: 0

logging:
  level.org.hibernate:
    SQL: DEBUG
    jdbc.bind: TRACE
    type.descriptor.sql.BasicBinder: TRACE
