server:
  # Turns off 'trace' field in HTTP body error-return
  error:
    include-stacktrace: never

spring:
  # Templates reloading during development launch
  thymeleaf:
    cache: false

  # Static resources reloading during development launch
  web:
    resources:
      cache.period: 0

  devtools:
    restart:
      enabled: true

  shell:
    interactive:
      enabled: true

logging:
  level.org:
    hibernate:
      SQL: DEBUG
      jdbc.bind: TRACE
      type.descriptor.sql.BasicBinder: TRACE

    springframework:
      security: DEBUG
      web: DEBUG
