CREATE TABLE vehicle_telemetry
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    timestamp   TIMESTAMP WITH TIME ZONE                NOT NULL,
    coordinates GEOMETRY(Point, 4326)                   NOT NULL,
    vehicle_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_vehicle_telemetry PRIMARY KEY (id)
);

ALTER TABLE vehicle_telemetry
    ADD CONSTRAINT FK_VEHICLE_TELEMETRY_ON_VEHICLE FOREIGN KEY (vehicle_id) REFERENCES vehicles (id);

INSERT INTO vehicle_telemetry (timestamp, coordinates, vehicle_id)
VALUES
    (NOW() - INTERVAL '1 hour', ST_SetSRID(ST_MakePoint(37.6173 + RANDOM() * 0.02 - 0.01, 55.7558 + RANDOM() * 0.02 - 0.01), 4326), 1),
    (NOW() - INTERVAL '2 hours', ST_SetSRID(ST_MakePoint(37.6185 + RANDOM() * 0.02 - 0.01, 55.7572 + RANDOM() * 0.02 - 0.01), 4326), 1),
    (NOW() - INTERVAL '3 hours', ST_SetSRID(ST_MakePoint(37.6190 + RANDOM() * 0.02 - 0.01, 55.7580 + RANDOM() * 0.02 - 0.01), 4326), 1),

    (NOW() - INTERVAL '1 hour', ST_SetSRID(ST_MakePoint(37.6200 + RANDOM() * 0.02 - 0.01, 55.7590 + RANDOM() * 0.02 - 0.01), 4326), 2),
    (NOW() - INTERVAL '2 hours', ST_SetSRID(ST_MakePoint(37.6215 + RANDOM() * 0.02 - 0.01, 55.7605 + RANDOM() * 0.02 - 0.01), 4326), 2),
    (NOW() - INTERVAL '3 hours', ST_SetSRID(ST_MakePoint(37.6220 + RANDOM() * 0.02 - 0.01, 55.7610 + RANDOM() * 0.02 - 0.01), 4326), 2),
    (NOW() - INTERVAL '4 hours', ST_SetSRID(ST_MakePoint(37.6230 + RANDOM() * 0.02 - 0.01, 55.7625 + RANDOM() * 0.02 - 0.01), 4326), 2),

    (NOW() - INTERVAL '1 hour', ST_SetSRID(ST_MakePoint(37.6240 + RANDOM() * 0.02 - 0.01, 55.7630 + RANDOM() * 0.02 - 0.01), 4326), 3),
    (NOW() - INTERVAL '2 hours', ST_SetSRID(ST_MakePoint(37.6255 + RANDOM() * 0.02 - 0.01, 55.7645 + RANDOM() * 0.02 - 0.01), 4326), 3),
    (NOW() - INTERVAL '3 hours', ST_SetSRID(ST_MakePoint(37.6260 + RANDOM() * 0.02 - 0.01, 55.7650 + RANDOM() * 0.02 - 0.01), 4326), 3),

    (NOW() - INTERVAL '1 hour', ST_SetSRID(ST_MakePoint(37.6270 + RANDOM() * 0.02 - 0.01, 55.7660 + RANDOM() * 0.02 - 0.01), 4326), 4),
    (NOW() - INTERVAL '2 hours', ST_SetSRID(ST_MakePoint(37.6285 + RANDOM() * 0.02 - 0.01, 55.7675 + RANDOM() * 0.02 - 0.01), 4326), 4),
    (NOW() - INTERVAL '3 hours', ST_SetSRID(ST_MakePoint(37.6290 + RANDOM() * 0.02 - 0.01, 55.7680 + RANDOM() * 0.02 - 0.01), 4326), 4),
    (NOW() - INTERVAL '4 hours', ST_SetSRID(ST_MakePoint(37.6300 + RANDOM() * 0.02 - 0.01, 55.7695 + RANDOM() * 0.02 - 0.01), 4326), 4),

    (NOW() - INTERVAL '1 hour', ST_SetSRID(ST_MakePoint(37.6310 + RANDOM() * 0.02 - 0.01, 55.7700 + RANDOM() * 0.02 - 0.01), 4326), 5),
    (NOW() - INTERVAL '2 hours', ST_SetSRID(ST_MakePoint(37.6325 + RANDOM() * 0.02 - 0.01, 55.7715 + RANDOM() * 0.02 - 0.01), 4326), 5),
    (NOW() - INTERVAL '3 hours', ST_SetSRID(ST_MakePoint(37.6330 + RANDOM() * 0.02 - 0.01, 55.7720 + RANDOM() * 0.02 - 0.01), 4326), 5);
